#!/usr/bin/env php
<?php

use Gt\Fetch\Http;
use Gt\Fetch\Response\BodyResponse;

if(!file_exists("vendor/autoload.php")) {
	echo "Please install dependencies using Composer" . PHP_EOL;
	exit(1);
}
require "vendor/autoload.php";

const VALID_HOST = "fonts.googleapis.com";
const VALID_QUERY = "family=";
const REGEX_CSS_PARTS = "/\/\*\s*(?<UNICODE_NAME>[^\s]+)\s*\*\/(?<CSS_LINES>[^}]*)/s";
const REGEX_FONT_FAMILY = "/font-family: [\"']([^\"']+)/";
const REGEX_FONT_STYLE = "/font-style: ([^;]+)/";
const REGEX_FONT_WEIGHT = "/font-weight: ([^;]+)/";
const REGEX_URI = "/src:.*url\(([^\)]*)/";
const REGEX_UNICODE_RANGE = "/unicode-range: ([^;]*)/";
const WEIGHT_NAMES = [
	"thin" => 100,
	"extra-light" => 200,
	"light" => 300,
	"regular" => 400,
	"medium" => 500,
	"semi-bold" => 600,
	"bold" => 700,
	"extra-bold" => 800,
	"heavy" => 900,
	"extra-black" => 950,
];

if($argc <= 1) {
	echo "Usage: download CSS_URI [FONT_PATH_PREFIX] [OUTPUT_TO]" . PHP_EOL;
	exit(2);
}

try {
	$uri = $argv[1] ?? null;
	checkUri($uri);
}
catch(RuntimeException $exception) {
	echo "Error: " . $exception->getMessage() . PHP_EOL;
	exit(3);
}

$fontPathPrefix = "/font";
if(isset($argv[2])) {
	$fontPathPrefix = $argv[2];
}

$outputTo = __DIR__ . "/font";
if(isset($argv[3])) {
	$outputTo = $argv[3];
}

echo "Downloading $uri ..." . PHP_EOL;

$data = [];

$ch = curl_init($uri);
curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$css = curl_exec($ch);
$data = parseCss($css);

$outputTo = rtrim($outputTo, "/");
if(!is_dir($outputTo)) {
	echo "Creating directory: $outputTo" . PHP_EOL;
	if(!mkdir($outputTo, 0775, true)) {
		exit(4);
	}
}
$outputTo = realpath($outputTo);
download($data, $outputTo);
writeSass($data, $outputTo, $fontPathPrefix);

function checkUri(string $uri):void {
	$components = parse_url($uri);

	if(!array_key_exists("host", $components)
		|| !array_key_exists("path", $components)
		|| !array_key_exists("query", $components)) {
		throw new RuntimeException("URI is not a valid for Google Fonts CSS");
	}

	if($components["host"] !== VALID_HOST) {
		throw new RuntimeException("Host is invalid - $components[host]");
	}

	if(!in_array($components["path"], ["/css", "/css2"], true)) {
		throw new RuntimeException("Path is invalid - $components[path]");
	}

	if(strpos($components["query"], VALID_QUERY) !== 0) {
		throw new RuntimeException("Query is invalid - $components[query]");
	}
}

function parseCss(string $css):array {
	if(!preg_match_all(REGEX_CSS_PARTS, $css, $matches)) {
		throw new RuntimeException("Failed parsing CSS");
	}

	$cssData = [];

	foreach($matches["UNICODE_NAME"] as $i => $unicodeName) {
		$fontFamily = null;
		$fontFamily = null;
		$fontStyle = null;
		$fontWeight = null;
		$woffUri = null;
		$unicodeRange = null;

		foreach(explode("\n", $matches["CSS_LINES"][$i]) as $line) {
			if(preg_match(REGEX_FONT_FAMILY, $line, $lineMatches)) {
				$fontFamily = $lineMatches[1];
			}
			if(preg_match(REGEX_FONT_STYLE, $line, $lineMatches)) {
				$fontStyle = $lineMatches[1];
			}
			if(preg_match(REGEX_FONT_WEIGHT, $line, $lineMatches)) {
				$fontWeight = $lineMatches[1];
			}
			if(preg_match(REGEX_URI, $line, $lineMatches)) {
				$woffUri = $lineMatches[1];
			}
			if(preg_match(REGEX_UNICODE_RANGE, $line, $lineMatches)) {
				$unicodeRange = $lineMatches[1];
			}
		}

		if(!isset($cssData[$fontFamily])) {
			$cssData[$fontFamily] = [];
		}

		if(!isset($cssData[$fontFamily][$unicodeName])) {
			$cssData[$fontFamily][$unicodeName] = [];
		}

		$cssData[$fontFamily][$unicodeName] []= [
			"style" => $fontStyle,
			"weight" => $fontWeight,
			"src" => $woffUri,
			"range" => $unicodeRange,
		];
	}

	return $cssData;
}

function getWeightName(string $cssWeight):string {
	$name = array_search($cssWeight, WEIGHT_NAMES);
	return $name ?: $cssWeight;
}

function getFontSlug(string $fontFamily):string {
	return strtolower(str_replace(" ", "-", $fontFamily));
}

function getFontFileName(string $fontFamily, string $unicodeName, array $properties):string {
	$fontSlug = getFontSlug($fontFamily);
	$weightName = getWeightName($properties["weight"]);
	return "$fontSlug-$weightName-$properties[style]-$unicodeName.woff2";
}

function download(array $data, string $outputTo):void {
	foreach($data as $fontFamily => $unicodeNames) {
		$lowercaseFontName = getFontSlug($fontFamily);
		$outputToWithFontName = "$outputTo/$lowercaseFontName";
		if(!is_dir($outputToWithFontName)) {
			mkdir($outputToWithFontName, 0775, true);
		}

		foreach($unicodeNames as $unicodeName => $definitions) {
			foreach($definitions as $properties) {
				$fileName = getFontFileName($fontFamily, $unicodeName, $properties);
				$pathName = "$outputTo/$lowercaseFontName/$fileName";

				$src = $properties["src"];
				if(empty($src)) {
					var_dump($properties);die();
				}
				echo $src . PHP_EOL;

				$ch = curl_init($src);
				curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
				curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0");
				$blob = curl_exec($ch);
				if(!is_dir(dirname($pathName))) {
					mkdir(dirname($pathName), 0775, true);
				}

				if(!file_put_contents($pathName, $blob)) {
					throw new RuntimeException("Failed writing font file: $pathName");
				}
			}
		}
	}
}

function writeSass(array $data, string $outputTo, string $fontPathPrefix):void {
	$outputTo = trim($outputTo);
	foreach($data as $fontFamily => $unicodeNames) {
		$lowercaseFontName = getFontSlug($fontFamily);
		$sassFileName = "$outputTo/$lowercaseFontName.scss";
		$sassContent = "";
		foreach($unicodeNames as $unicodeName => $definitions) {
			foreach($definitions as $properties) {
				$fileName = getFontFileName($fontFamily, $unicodeName, $properties);
				$unicodeRange = $properties["range"];
				$sassContent .= <<<SASS
@font-face {
	font-family: "$fontFamily";
	font-style: $properties[style];
	font-weight: $properties[weight];
	font-display: swap;
	src: url("$fontPathPrefix/$lowercaseFontName/$fileName") format("woff2");
	unicode-range: $unicodeRange;
}

SASS;
			}
		}

		file_put_contents($sassFileName, $sassContent);
	}
}
